# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã¯ãƒ•ãƒ«ãƒ‘ã‚¹ã§è¡¨ç¤ºã•ã›ãŸã„
# ãƒ•ãƒ«ãƒ‘ã‚¹ã ã¨é•·ã™ãã‚‹ã“ã¨ãŒã‚ã‚‹ã®ã§ã€2è¡Œç›®ã¯ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã ã‘è¡¨ç¤ºã™ã‚‹
format = '$all$directory$character'

[aws]
format = ", [$symbol($profile)(\\($region\\))(\\[$duration)]($style)"
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[bun]
format = ", [$symbol($version)]($style)"

[c]
format = ", [$symbol($version(-$name))]($style)"
symbol = "î˜ "

[character]
error_symbol = "\n[\\$](bold red)"
success_symbol = "\n[\\$](bold green)"

[cmake]
format = ", [$symbol($version)]($style)"

[cmd_duration]
format = ", [â± $duration]($style)"

[cobol]
format = ", [$symbol($version)]($style)"

[conda]
format = ", [$symbol$environment]($style)"
symbol = "ï„Œ "

[crystal]
format = ", [$symbol($version)]($style)"
symbol = "î˜¯ "

[daml]
format = ", [$symbol($version)]($style)"

[dart]
format = ", [$symbol($version)]($style)"
symbol = "î˜ "

[deno]
format = ", [$symbol($version)]($style)"

[directory]
truncation_length = 0
truncate_to_repo = false
format = "\n[$path]($style)[$read_only]($read_only_style) "
read_only = " ó°Œ¾"

[docker_context]
format = ", [$symbol$context]($style)"
symbol = "ïŒˆ "

[dotnet]
format = ", [$symbol($version)(ğŸ¯ $tfm)]($style)"

[elixir]
format = ", [$symbol($version \\(OTP $otp_version\\))]($style)"
symbol = "î‰µ "

[elm]
format = ", [$symbol($version)]($style)"
symbol = "î˜¬ "

[erlang]
format = ", [$symbol($version)]($style)"

[fennel]
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

[gcloud]
format = ", [$symbol$account(@$domain)(\\($region\\))]($style)"

[git_branch]
format = ", [$symbol$branch]($style)"
symbol = "ï˜ "

[git_metrics]
added_style = 'bold blue'
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[golang]
format = ", [$symbol($version)]($style)"
symbol = "î˜§ "

[guix_shell]
format = ", [$symbol]($style)"
symbol = "ïŒ¥ "

[haskell]
format = ", [$symbol($version)]($style)"
symbol = "î· "

[haxe]
format = ", [$symbol($version)]($style)"
symbol = "î™¦ "

[helm]
format = ", [$symbol($version)]($style)"

[hg_branch]
format = ", [$symbol$branch]($style)"
symbol = "ï˜ "

[hostname]
ssh_only = false
ssh_symbol = "î¬ "

[java]
format = ", [$symbol($version)]($style)"
symbol = "î‰– "

[julia]
format = ", [$symbol($version)]($style)"
symbol = "î˜¤ "

[kotlin]
format = ", [$symbol($version)]($style)"
symbol = "î˜´ "

[kubernetes]
format = ", [$symbol$context( \\($namespace\\))]($style)"

[line_break]
disabled = true

[lua]
format = ", [$symbol($version)]($style)"
symbol = "î˜  "

[memory_usage]
disabled = false
format = ", $symbol[$ram( | $swap)]($style)"
symbol = "ó°› "

[meson]
format = ", [$symbol$project]($style)"
symbol = "ó°”· "

[nim]
format = ", [$symbol($version)]($style)"
symbol = "ó°†¥ "

[nix_shell]
format = ", [$symbol$state( \\($name\\))]($style)"
symbol = "ïŒ“ "

[nodejs]
format = ", [$symbol($version)]($style)"
symbol = "îœ˜ "

[ocaml]
format = ", [$symbol($version)(\\($switch_indicator$switch_name\\))]($style)"
symbol = "î™º "

[opa]
format = ", [$symbol($version)]($style)"

[openstack]
format = ", [$symbol$cloud(\\($project\\))]($style)"

[os]
format = ", [$symbol]($style)"
disabled = false

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[package]
format = ", [$symbol$version]($style)"
symbol = "ó°— "

[perl]
format = ", [$symbol($version)]($style)"
symbol = "î™¾ "

[php]
format = ", [$symbol($version)]($style)"
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "

[pulumi]
format = ", [$symbol$stack]($style)"

[purescript]
format = ", [$symbol($version)]($style)"

[python]
format = ", [${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)"
python_binary = "python3"
symbol = "îˆµ "

[raku]
format = ", [$symbol($version-$vm_version)]($style)"

[red]
format = ", [$symbol($version)]($style)"

[rlang]
symbol = "ó°Ÿ” "

[ruby]
format = ", [$symbol($version)]($style)"
symbol = "î‘ "

[rust]
format = ", [$symbol($version)]($style)"
symbol = "î¨ "

[scala]
format = ", [$symbol($version)]($style)"
symbol = "îœ· "

[shell]
disabled = false

[shlvl]
disabled = false
format = '[$symbol$shlvl]($style) '
symbol = "ï„  "
threshold = 1

[spack]
format = ", [$symbol$environment]($style)"
symbol = "ğŸ…¢ "

[sudo]
disabled = false
format = ", [$symbol]($style)"
symbol = "ğŸ¦¸ "

[swift]
format = ", [$symbol($version)]($style)"
symbol = "î• "

[terraform]
format = ", [$symbol$workspace]($style)"

[time]
format = ", [$time]($style)"

[username]
show_always = true

[vagrant]
format = ", [$symbol($version)]($style)"

[vlang]
format = ", [$symbol($version)]($style)"

[zig]
format = ", [$symbol($version)]($style)"
